### ISSUE TITLE
Failed to load routines in SDL2

### ISSUE THREAD

**Issue by shawnpringle** [gAndy50/EuSDL2#1]
Hello I ran my handy wrapper scanner from  [Euphoria Tools](/shawnpringle/euphoriatools), and got this output:

It turns out some of these things are just not available on my platform and some of these may be implemented in the C headers as macros  Even so this tool mentioned though can be a good for finding actual errors.  There are only 48 here.  I found four that were a problem due to spelling errors.

Could not load '+SDL_WinRTRunApp' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 84, column 43.
Could not load '+SDL_TriggerBreakpoint' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 352, column 49.
Could not load '+SDL_assert' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 353, column 38.
Could not load '+SDL_assert_paranoid' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 354, column 47.
Could not load '+SDL_assert_release' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 355, column 46.
Could not load '+SDL_RendercopyEx' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1087, column 44.
Could not load '+SDL_GetTextureSCaleMode' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1532, column 51.
Could not load '+SDL_GetRBA' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1555, column 39.
Could not load '+SDL_IntersectRectAndLinr' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1652, column 52.
Could not load '+SDL_PointInRect' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1653, column 43.
Could not load '+SDL_RectEmpty' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1654, column 41.
Could not load '+SDL_RectEquals' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1655, column 42.
Could not load '+SDL_writeLE32' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1731, column 41.
Could not load '+SDL_BlitScaled' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1927, column 54.
Could not load '+SDL_BlitSurface' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1928, column 43.
Could not load '+SDL_LoadBMP' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1942, column 39.
Could not load '+SDL_MUSTLOCK' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1947, column 40.
Could not load '+SDL_SaveBMP' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1948, column 39.
Could not load '+SDL_CreateRGBSurfaceWithFormatForm' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 1966, column 62.
Could not load '+SDL_GetEventState' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 2251, column 45.
Could not load '+SDL_QuitRequested' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 2263, column 45.
Could not load '+SDL_GameControllerAddMappingsFromFile' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 2971, column 65.
Could not load '+SDL_LoadWAV' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 3462, column 39.
Could not load '+SDL_AtomicDecRef' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 3966, column 44.
Could not load '+SDL_AtomicIncRef' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 3969, column 44.
Could not load '+SDL_CompilerBarrier' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 3975, column 47.
Could not load '+SDL_TICKS_PASSED' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4063, column 44.
Could not load '+SDL_Swap16' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4298, column 50.
Could not load '+SDL_Swap32' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4299, column 38.
Could not load '+SDL_Swap64' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4300, column 38.
Could not load '+SDL_SwapBE16' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4301, column 40.
Could not load '+SDL_SwapBE32' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4302, column 40.
Could not load '+SDL_SwapBE64' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4303, column 40.
Could not load '+SDL_SwapFloat' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4304, column 41.
Could not load '+SDL_SwapFloatBE' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4305, column 43.
Could not load '+SDL_SwapFloatLE' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4306, column 43.
Could not load '+SDL_SwapLE16' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4307, column 40.
Could not load '+SDL_SwapLE32' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4308, column 40.
Could not load '+SDL_SwapLE64' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4309, column 40.
Could not load '+SDL_MostSignificantBitIndex32' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4385, column 69.
Could not load '+SDL_AndroidGetActivity' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4405, column 62.
Could not load '+SDL_AndroidGetExternalStoragePath' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4406, column 61.
Could not load '+SDL_AndroidGetExternalStorageState' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4407, column 62.
Could not load '+SDL_AndroidGetInternalStoragePath' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4408, column 61.
Could not load '+SDL_AndroidGetJNIEnv' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4409, column 48.
Could not load '+SDL_WinRTGetFSPathUNICODE' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4414, column 53.
Could not load '+SDL_WinRTGetFSPathUTF8' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4415, column 50.
Could not load '+SDL_WinRTGetDeviceFamily' from 'SDL2.dll' in '../EuSDL2/EuSDL2.ew' line 4416, column 52.
There were 643 C-routines checked and 595 were successful.

**Comment by gAndy50** [comment]
Hello,

thanks for the heads up. I will address these issues ASAP. 

NOTE: SDL_BlitSurface is replaced by UpperBlitSurface, I mention this in the wrapper's source code. I have kept SDL_BlitSurface wrapped for legacy reasons.

**Comment by gAndy50** [comment]
I have fixed the typos. I checked and it runs fine under my system as well as the demos. I'm running Windows 7 64-bit. Some platform specific functions may not work under certain systems.

**Comment by shawnpringle** [comment]
Take a look at the PR request from the OpenEuphoria account.

**Comment by gAndy50** [comment]
I've closed this as the issue has been fixed.
